before_script:
  - cp bluej/build.properties.template bluej/build.properties
  - sed -i 's/build_java_home=.*/build_java_home=\/usr\/lib\/jvm\/java-8-oracle\//' bluej/build.properties

stages:
 - build

variables:
  JAVA_HOME: /usr/lib/jvm/java-8-oracle

antbuild:
  stage: build
  script:
    - cd bluej && ant rebuild-ready && xvfb-run ant test
    - cd ../greenfoot && ant clean && ant ready-to-run && xvfb-run ant test